[build]
  command = "yarn generate"
  publish = ".output/public"

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
